# Generated by Django 5.1.1 on 2024-09-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="parsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="resume",
            name="technologies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
    ]
