# Generated by Django 5.0 on 2024-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_resume_education_resume_email_resume_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="college",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="designation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="total_experience",
            field=models.FloatField(default=0),
        ),
    ]
