# name of the workflow
name: resume-parsing-application CI/CD

# which event will trigger this workflow
on:
    push:
        branches: [main]

# jobs to perform when the workflow is triggered
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v2 # this action checks out the repo, so that the workflow can access it

            - name: Set up Python ${{matrix.python-version}}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  python manage.py test

    build:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/resume-parser:latest
